server:
  port: 8888

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service_to_service
          uri: lb://stream-translate
          predicates:
            - Path=/translate/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/

