
server:
  port: 8000

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000

  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



# ===========================================================================================
logging.level.ROOT: INFO
logging.level.org.springframework.web: INFO
logging.level.cn.com.waterelephant: INFO

logging.path: /Users/admin/logs/backup
logging.file: /Users/admin/logs/media/${spring.application.name}.log

logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss} - [${spring.application.name:},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] - %msg%n'
logging.pattern.file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] - [${spring.application.name:},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] - %-5level %logger{36} - %msg%n'
