-- MySQL Script generated by MySQL Workbench
-- Wed Jul 31 14:31:26 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Translate
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Translate` ;

-- -----------------------------------------------------
-- Schema Translate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Translate` DEFAULT CHARACTER SET utf8 ;
USE `Translate` ;

-- -----------------------------------------------------
-- Table `Translate`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Translate`.`event` ;

CREATE TABLE IF NOT EXISTS `Translate`.`event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `resource_id` VARCHAR(64) NULL,
  `resource_name` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Translate`.`translate_biz_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Translate`.`translate_biz_info` ;

CREATE TABLE IF NOT EXISTS `Translate`.`translate_biz_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) NULL,
  `src_file_path` VARCHAR(256) NULL COMMENT '源文件路径',
  `src_file_name` VARCHAR(128) NULL COMMENT '源文件名称',
  `target_bite_rate` VARCHAR(32) NULL COMMENT '目标分辨率',
  `target_file_name` VARCHAR(128) NULL,
  `upload_file_path` VARCHAR(256) NULL COMMENT '上传路径',
  `is_proportion` TINYINT(1) NULL COMMENT '是否等比例',
  `status` TINYINT(2) NULL COMMENT '转码状态：0未就绪，1转码中，2转码已完成，3转码失败，4上传失败，5上传成功',
  `file_format` VARCHAR(8) NULL COMMENT '文件格式',
  `event_id` BIGINT NOT NULL COMMENT '外键',
  PRIMARY KEY (`id`, `event_id`),
  INDEX `fk_translate_biz_info_event_idx` (`event_id` ASC),
  CONSTRAINT `fk_translate_biz_info_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `Translate`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Translate`.`translate_record_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Translate`.`translate_record_info` ;

CREATE TABLE IF NOT EXISTS `Translate`.`translate_record_info` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
